---
- name: System: Disable Smart Quotes 
  tags: defaults
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    value: 0
    state: present

- name: System: Disable Smart Dashes
  tags: defaults
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    value: 0
    state: present

- name: System: Disable Auto Capitalization
  tags: defaults
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    value: 0
    state: present

- name: System: Disable Automatic Periods
  tags: defaults
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    value: 0
    state: present

- name: Desktop Services - don't write .DS_Store files on removable drives
  tags: defaults
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: false
    state: present

- name: Desktop Services - don't write .DS_Store files on network drives
  tags: defaults
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: false
    state: present

- name: Finder - new windows start in home directory
  tags: defaults
  osx_defaults: 
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "PfHm"
    state: present 

- name: Finder - don't warn before emptying trash
  tags: defaults
  osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: false
    state: present

- name: Finder - use list view by default
  tags: defaults 
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "Nlsv"
    state: present

- name: Finder - disable warning on file extension change
  tags: defaults
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
    state: present

- name: Finder - enable path bar
  tags: defaults
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
    state: present

- name: Dock - Auto-Hide the dock
  tags: defaults
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    state: present

- name: Dock - Don't show recent applications
  tags: defaults
  osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false
    state: present

- name: Trackpad - Disable natural scrolling
  tags: defaults
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false
    state: present

