---
- name: MacOS - disable smart quotes
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: "false"

- name: Desktop Services - don't write .DS_Store files on removable drives
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: "false"

- name: Desktop Services - don't write .DS_Store files on network drives
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: "false"


- name: Finder - new windows start in home directory
  osx_defaults: 
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "PfHm" 

- name: Finder - don't warn before emptying trash
  osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: "false"

- name: Finder - use list view by default
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "Nlsv"

- name: Finder - disable warning on file extension change
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: "false"

- name: Finder - enable path bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: "true"

- name: Dock - Auto-Hide the dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: "true"

- name: Dock - Don't show recent applications
  osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: "false"

 
